name: mypy

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ruff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.11", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --force-reinstall -r requirements/lint.txt
        pip install redis
        pip install setuptools
        pip install pyzmq
        pip install --no-cache-dir --force-reinstall types-setuptools==80.4.0.20250511
    - name: Mypy
      run: |
        mypy
        mypy tests --follow-imports skip
        mypy lmcache --follow-imports skip